Feature: Cart
AccentureJace/lozodo_revamp pull request #13
Opened 2024-12-03 03:10 UTC by jason-villa-accenture

Modified:
src\routes\index.jsx
src\routes\endpoints.js

Added:
src\pages\user\Cart.jsx
src\components\cart
src\components\cart\CartCard.jsx
src\components\cart\CartSummary.jsx
src\components\cart\index.js

2024-12-03 03:52 UTC, AccentureJace requested changes
Please see request changes

2024-12-03 03:52 UTC, AccentureJace commented on src/components/cart/CartCard.jsx
> +import PRODUCT_IMAGE from '../../assets/images/product_1.webp';
utilize index.js

2024-12-03 03:52 UTC, AccentureJace commented on src/constants/routes/index.js
> +export const CART = '/cart';
this should be PATH_CART

2024-12-03 03:52 UTC, AccentureJace commented on src/pages/user/Cart.jsx
> +import { CartCard, CartSummary } from '../../components/cart';
follow import ordering

2024-12-03 03:52 UTC, AccentureJace commented on src/routes/index.jsx
> +import Cart from '../pages/user/Cart';
utilize index.js

2024-12-03 03:52 UTC, AccentureJace commented on src/components/cart/CartCard.jsx
create index.js file inside cart folder.
import also the files in the component's index.js. refer to apps and products index.js and components' index.js

2024-12-03 03:55 UTC, jason-villa-accenture commented on src/components/cart/CartCard.jsx
> +import PRODUCT_IMAGE from '../../assets/images/product_1.webp';
done.

2024-12-03 03:55 UTC, jason-villa-accenture commented on src/constants/routes/index.js
> +export const CART = '/cart';
done.

2024-12-03 03:57 UTC, jason-villa-accenture commented on src/pages/user/Cart.jsx
> +import { CartCard, CartSummary } from '../../components/cart';
done

2024-12-03 04:01 UTC, jason-villa-accenture commented on src/routes/index.jsx
> +import Cart from '../pages/user/Cart';
done.

2024-12-03 04:04 UTC, jason-villa-accenture commented on src/components/cart/CartCard.jsx
done

2024-12-03 04:12 UTC, AccentureJace approved these changes
LGTM

2024-12-08 22:48 UTC, AccentureAngelo approved these changes

2024-12-09 08:37 UTC, closed without merging

2024-12-09 08:38 UTC, AccentureJace commented
Closing this PR since this is no longer applicable.