Feature: Signup Page
AccentureJace/lozodo_revamp pull request #17
Opened 2024-12-05 06:00 UTC by analou-mae

Added Files: 
src/pages/auth/Signup.jsx
src/constants/auth/index.js

Updated Files:
src/pages/auth/Signin.jsx
src/utils/index.js
src/routes/index.js
src/App.jsx
src/constants/routes/index.js

2024-12-05 06:40 UTC, AccentureJace requested changes
Please see request changes

2024-12-05 06:40 UTC, AccentureJace commented on src/constants/auth/index.js
> +export const CONFIRM_PASSOWRD_ERROR = 'Passwords do not match.';
Follow this naming convention

export const VALIDATION_CONFIRM_PASSWORD
export const VALIDATION_FIRST_NAME

export const SUCCESS_SIGNUP

export const VALIDATION_USERNAME

2024-12-05 06:40 UTC, AccentureJace commented on src/pages/auth/Signup.jsx
> +        const validation_errors = validateObject(values);
Does the global validations applicable to this one or we need separate validations?

2024-12-05 06:40 UTC, AccentureJace commented on src/utils/index.js
> +            return Promise.reject(new Error(CONFIRM_PASSOWRD_ERROR));
follow the variable name in the constants for consistency

2024-12-05 06:40 UTC, AccentureJace commented on src/utils/index.js
> +            return Promise.reject(new Error(CONFIRM_PASSOWRD_ERROR));
use async await instead of Promise

2024-12-05 07:57 UTC, AccentureJace requested changes
Please see request changes

2024-12-05 07:57 UTC, AccentureJace commented on src/constants/auth/index.js
> +export const SUCCESS_SIGNUP = 'User registered successfully';
separate this from VALIDATION by adding next line

2024-12-05 07:57 UTC, AccentureJace commented on src/constants/auth/index.js
> +export const INVALID_USERNAME = 'Invalid Username';
separate this from SUCCESS by adding next line

2024-12-05 07:57 UTC, AccentureJace commented on src/constants/auth/index.js
> +export const SERVER_ERROR = 'An error occurred. Please try again later.';
ERROR_SERVER

2024-12-05 07:57 UTC, AccentureJace commented on src/pages/auth/Signup.jsx
> +            if (response.message === SUCCESS_SIGNUP) {
utilize destructure

const { message, response } = response

2024-12-05 07:57 UTC, AccentureJace commented on src/pages/auth/Signup.jsx
> +                toast.error(response.response.data.error.message);
utilize destructure

const { message as ___ } = response.data.error

2024-12-06 05:29 UTC, AccentureJace approved these changes
LGTM

2024-12-06 08:10 UTC, AccentureAngelo approved these changes

2024-12-06 09:03 UTC, merged