Feature: Login Page
AccentureJace/lozodo_revamp pull request #8
Opened 2024-12-02 09:15 UTC by analou-mae

Added Files: 
     components/auth/AuthForm.jsx
     constants/auth/index.js
     assets/images/sign-in_icon.svg
Updated Files: 
     pages/user/Signin.jsx
     components/index.js
     components/routes/endpoints/js

2024-12-02 13:27 UTC, AccentureJace requested changes
Please see request changes

2024-12-02 13:27 UTC, AccentureJace commented on src/assets/images/sign-in_icon.svg
Remove this and utilize the react-icons

2024-12-02 13:27 UTC, AccentureJace commented on src/components/auth/AuthForm.jsx
> +import React from 'react';
Remove unused imports

2024-12-02 13:27 UTC, AccentureJace commented on src/components/auth/AuthForm.jsx
> +import Form from 'antd/es/form/Form';
Please check if we can add this from 'antd'

2024-12-02 13:27 UTC, AccentureJace commented on src/components/auth/AuthForm.jsx
> +import Input from 'antd/es/input/Input';
Please check if we can add this from 'antd'

2024-12-02 13:27 UTC, AccentureJace commented on src/components/auth/AuthForm.jsx
> +const AuthForm = ({
Please use props as arguments and then destruct the props in the next line

2024-12-02 13:27 UTC, AccentureJace commented on src/components/auth/AuthForm.jsx
> +            {isSignIn ? (
use ?? instead of ternary

2024-12-02 13:27 UTC, AccentureJace commented on src/components/auth/AuthForm.jsx
> +            {fields.map((field) => (
Why map the fields if it is a static field? Directly add the fields in the components instead of mapping.

2024-12-02 13:27 UTC, AccentureJace commented on src/components/auth/AuthForm.jsx
> +                    className='tw-w-full tw-bg-[#0D99FF] tw-text-[#FFFCFC] tw-font-bold tw-text-center tw-py-3 tw-rounded-lg'
specify if white or blue. do not use hex

2024-12-02 13:27 UTC, AccentureJace commented on src/constants/auth/index.js
Remove this since we will use static fields in auth form

2024-12-02 13:27 UTC, AccentureJace commented on src/pages/user/Signin.jsx
> +import React, { useState } from 'react';
Remove unused imports

2024-12-02 13:27 UTC, AccentureJace commented on src/pages/user/Signin.jsx
> +import authService from '../../services/auth';
use the services index.js it should be import {authService} from '../../services'

2024-12-02 13:27 UTC, AccentureJace commented on src/pages/user/Signin.jsx
> +import { Bounce, ToastContainer, toast } from 'react-toastify';
configure ToastContainer in app.jsx not here

2024-12-02 13:27 UTC, AccentureJace commented on src/pages/user/Signin.jsx
> +import Icon from '../../assets/images/sign-in_icon.svg';
use react icons instead of image

2024-12-02 13:27 UTC, AccentureJace commented on src/pages/user/Signin.jsx
> +                console.log('Login successful:', response);
remove console.log

2024-12-02 13:27 UTC, AccentureJace commented on src/pages/user/Signin.jsx
> +                console.log('Login failed:', response.status.message);
remove console.log use toast

2024-12-02 13:27 UTC, AccentureJace commented on src/pages/user/Signin.jsx
> +                console.log('Login failed with status:', response.status);
remove console.log use toast

2024-12-02 13:27 UTC, AccentureJace commented on src/pages/user/Signin.jsx
> +            console.error('Login failed:', error.message);
remove console.error use toast

2024-12-02 13:27 UTC, AccentureJace commented on src/pages/user/Signin.jsx
> +                <AuthForm
double check with AuthForm comments if some props is still applicable

2024-12-02 13:27 UTC, AccentureJace commented on src/pages/user/Signin.jsx
> +                        className='tw-text-[#0D99FF] tw-font-semibold tw-cursor-pointer tw-text-sm md:tw-text-base'
specify if white or blue. do not use hex

2024-12-02 13:27 UTC, AccentureJace commented on src/routes/endpoints.js
Kindly pull dev branch. the constants of the endpoints can now be found in constants folder.

2024-12-02 13:27 UTC, AccentureJace commented on src/routes/index.jsx
> +        path: ENDPOINTS.PATH_LOGIN,
please update the path. refer to the constants folder

2024-12-02 13:27 UTC, AccentureJace commented on src/pages/user/Signin.jsx
change the folder name from user to auth

2024-12-02 13:27 UTC, AccentureJace commented on src/routes/index.jsx
> +import Signin from '../pages/user/Signin';
utilize index.js

2024-12-03 03:46 UTC, AccentureJace requested changes
Please see request changes

2024-12-03 03:46 UTC, AccentureJace commented on src/assets/images/sign-in_icon.svg
delete this if not used

2024-12-03 03:46 UTC, AccentureJace commented on src/routes/index.jsx
> +import Signin from '../pages/auth/Signin';
create index.js and add SignIn page there. Expected input here is:
import { Signin } from '../pages';

2024-12-03 04:04 UTC, AccentureJace approved these changes
LGTM

2024-12-03 04:42 UTC, AccentureAngelo commented on src/pages/auth/Signin.jsx
> +    const handleSubmitForm = async (values) => {
lipat natin to sa hooks natin

2024-12-05 05:48 UTC, AccentureAngelo approved these changes

2024-12-05 06:44 UTC, merged